#!/bin/bash
#set -vx
## build-ovpn - Make OpenVPN client configuration file
## Usage: build-ovpn [CLIENT]
##   CLIENT: clientname (will be asked if not given or set in $UVPN_NAME)

[[ $- == *i* ]] && echo "ABORT: run as script, don't source" && return 1
((EUID)) && echo "ABORT: must have root privileges" && exit 2
self="$(readlink -e "$0")"

source ${self%/*}/vars

name=$UVPN_NAME
: ${name:=$1}
while [[ ! $name ]] || [[ $name = server || $name = ta || $name = ca ]]
do
	[[ $name ]] && echo "Client name '$name' is unacceptable"
	read -rp "Give proper client name: " name
done

[[ -z $WAN ]] &&
	echo "ABORT: WAN in vars must be set to external DN/IP(s) of the server" &&
	exit 3
REMOTE=
for wan in $WAN
do
	IFS=':' read url port <<<"$wan"
  REMOTE+="remote $url $port"$'\n'
done

if [[ $DHCP_RANGE ]]
then
	getroute=($(ip route get 8.8.8.8))
	: ${GW:=${getroute[2]}}
	if [[ -z $MASK ]]
	then
		: ${DEV:=${getroute[4]}}
		MASK=$(ifconfig $DEV |sed 's/^.*Mask://' |grep '^[0-9.]*.$')
	fi
	start=${DHCP_RANGE%-*} end=${DHCP_RANGE#*-}
	bridge="server-bridge $GW $MASK ${GW%.*}.$start ${GW%.*}.$end"
fi

ovpn="$KEY_DIR/$name.ovpn"
cafile="$KEY_DIR/ca.crt"
tafile="$KEY_DIR/ta.key"
! [[ -f "$cafile" && -f "$tafile" ]] && echo "ABORT: first run ${self%/*}/build-server" && exit 4
ca=$(cat "$cafile")
ta=$(cat "$tafile" |grep -v '^#')

crtfile="$KEY_DIR/$name.crt"
keyfile="$KEY_DIR/$name.key"
! [[ -f "$crtfile" && -f "$keyfile" ]] && "$EASY_RSA/pkitool" "$name"
crt=$(sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' "$crtfile")
key=$(cat "$keyfile")
[[ -z $crt || -z $key ]] && echo "ABORT: certificate or key not generated" && exit 5

cat <<-EOF >"$ovpn"
	client
	dev tun
	proto udp
	${REMOTE}resolv-retry infinite
	nobind
	persist-key
	persist-tun
	$bridge
	remote-cert-tls server
	; tls-version-min 1.2
	key-direction 1
	verify-x509-name $KEY_NAME name
	cipher AES-256-CBC
	auth SHA256
	comp-lzo
	verb 4
	<ca>
	$ca
	</ca>
	<cert>
	$crt
	</cert>
	<key>
	$key
	</key>
	<tls-auth>
	$ta
	</tls-auth>
EOF

echo "Client configuration file '$ovpn' done"

exit 0
