#!/bin/bash
#set -vx
## build-ovpn - Make OpenVPN client configuration file
## Usage: build-ovpn [CLIENT]
##   CLIENT: clientname (will be asked if not given or set in $UVPN_NAME)
## Variables imported from vars: WAN KEY_DIR EASY_RSA

[[ $- == *i* ]] && echo "ABORT: run as script, don't source" && return 1
((EUID)) && echo "ABORT: must have root privileges" && exit 2
dir="$(readlink -e "$0")" dir=${dir%/*}

source "$dir/vars"

[[ -z $WAN ]] &&
	echo "ABORT: WAN in vars must be set to external DN/IP(s) of the server" &&
	exit 3
name=$UVPN_NAME
: ${name:=$1}
while [[ ! $name ]] || [[ $name = server || $name = ta || $name = ca ]]
do
	[[ $name ]] && echo "Client name '$name' is unacceptable"
	read -rp "Give proper client name: " name
done

remote=
for wan in $WAN
do
	IFS=':' read url port <<<"$wan"
  remote+="remote $url $port"$'\n'
done

ovpn="$KEY_DIR/$name.ovpn"
cafile="$KEY_DIR/ca.crt"
tafile="$KEY_DIR/ta.key"
! [[ -f "$cafile" && -f "$tafile" ]] && echo "ABORT: Run $dir/build-server first" && exit 4
ca=$(cat "$cafile")
ta=$(cat "$tafile" |grep -v '^#')

crtfile="$KEY_DIR/$name.crt"
keyfile="$KEY_DIR/$name.key"
! [[ -f "$crtfile" && -f "$keyfile" ]] && "$EASY_RSA/pkitool" "$name"
crt=$(sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' "$crtfile")
key=$(cat "$keyfile")
[[ -z $crt || -z $key ]] && echo "ABORT: certificate or key not generated" && exit 5

cat <<-EOF >"$ovpn"
	client
	dev tun
	proto udp
	${remote}resolv-retry infinite
	nobind
	persist-key
	persist-tun
	$bridge
	remote-cert-tls server
	; tls-version-min 1.2
	key-direction 1
	verify-x509-name $KEY_NAME name
	cipher AES-256-CBC
	auth SHA256
	comp-lzo
	verb 4
	<ca>
	$ca
	</ca>
	<cert>
	$crt
	</cert>
	<key>
	$key
	</key>
	<tls-auth>
	$ta
	</tls-auth>
EOF

echo "Client configuration file '$ovpn' done"

exit 0
